// utils/buildSynnexPO.js
import { create } from "xmlbuilder2";

export const buildSynnexPO = (order) => {
  const doc = create({ version: "1.0", encoding: "UTF-8" })
    .ele("SynnexB2B")
    .ele("Credential")
    .ele("UserID")
    .txt(process.env.SYNNEX_USERNAME)
    .up()
    .ele("Password")
    .txt(process.env.SYNNEX_PASSWORD)
    .up()
    .up()
    .ele("OrderRequest")
    .ele("CustomerNumber")
    .txt(process.env.SYNNEX_CUSTOMER_NO)
    .up()
    .ele("PONumber")
    .txt(`BB-${order.id}`)
    .up()
    .ele("DropShipFlag")
    .txt("Y")
    .up()
    .ele("Shipment")
    .ele("ShipTo")
    .ele("AddressName1")
    .txt(order.shipping_address.name || "Unnamed")
    .up()
    .ele("AddressLine1")
    .txt(order.shipping_address.address1)
    .up()
    .ele("City")
    .txt(order.shipping_address.city)
    .up()
    .ele("State")
    .txt(order.shipping_address.province_code)
    .up()
    .ele("ZipCode")
    .txt(order.shipping_address.zip)
    .up()
    .ele("Country")
    .txt(order.shipping_address.country_code)
    .up()
    .up()
    .ele("ShipToContact")
    .ele("ContactName")
    .txt(order.shipping_address.name || "Unnamed")
    .up()
    .ele("PhoneNumber")
    .txt(order.shipping_address.phone || "0000000000")
    .up()
    .ele("EmailAddress")
    .txt(order.email || "no-reply@example.com")
    .up()
    .up()
    .ele("ShipMethod")
    .ele("Code")
    .txt("FG")
    .up()
    .up()
    .up()
    .ele("Payment")
    .ele("BillTo", { code: process.env.SYNNEX_CUSTOMER_NO })
    .up()
    .up()
    .ele("Items");

  order.line_items.forEach((item, idx) => {
    doc
      .last()
      .ele("Item", { lineNumber: idx + 1 })
      .ele("SKU")
      .txt(item.sku || "UNKNOWN-SKU")
      .up()
      .ele("UnitPrice")
      .txt(item.price)
      .up()
      .ele("OrderQuantity")
      .txt(item.quantity)
      .up()
      .up();
  });

  return doc.end({ prettyPrint: true });
};
